In [1]:
import numpy as np
import tensorflow.keras as keras
from sklearn.utils import shuffle
import matplotlib.pyplot as plt

In [2]:
X = np.load("F:\\Dataset\\chess\\X.npy")[0:550000]
Y = np.load("F:\\Dataset\\chess\\Y.npy")[0:550000]

In [19]:
print(X[0])

[[[0 0 0 1 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 1 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 1 0 0 0 0 0 0 0]
  [0 0 0 0 0 1 0 0 0 0 0 0]
  [0 0 1 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 1 0 0 0 0 0 0 0 0]]

 [[1 0 0 0 0 0 0 0 0 0 0 0]
  [1 0 0 0 0 0 0 0 0 0 0 0]
  [1 0 0 0 0 0 0 0 0 0 0 0]
  [1 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0]
  [1 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0]
  [1 0 0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0]
  [0 1 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0]
  [0 1 0 0 0 0 0 0 0 0 0 0]
  [1 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0]
  [1 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 1 0 0 0 0 0]
  [0 0 0 0 0

In [18]:
X = X.reshape((-1, 8, 8, 12))
Y = (np.argmax(Y, axis=1) == 1) * 1.0
print(len(X))

AxisError: axis 1 is out of bounds for array of dimension 1

In [16]:
# kernel_regularizer=keras.regularizers.L1(0.001),
model = keras.Sequential()
model.add(keras.layers.Conv2D(32, (5,5), padding='same', input_shape=(8, 8, 12)))
model.add(keras.layers.ReLU())

model.add(keras.layers.Conv2D(32, (5,5), padding='same'))
model.add(keras.layers.ReLU())

model.add(keras.layers.Conv2D(32, (5,5), padding='same'))
model.add(keras.layers.ReLU())

model.add(keras.layers.Flatten())

model.add(keras.layers.Dense(64, activation="relu"))
model.add(keras.layers.Dense(1, activation="sigmoid"))

opt = keras.optimizers.Adam(learning_rate=0.0001)
model.compile(loss='binary_crossentropy', optimizer=opt, metrics=["accuracy"])

model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_8 (Conv2D)           (None, 8, 8, 32)          9632      
                                                                 
 re_lu_8 (ReLU)              (None, 8, 8, 32)          0         
                                                                 
 conv2d_9 (Conv2D)           (None, 8, 8, 32)          25632     
                                                                 
 re_lu_9 (ReLU)              (None, 8, 8, 32)          0         
                                                                 
 conv2d_10 (Conv2D)          (None, 8, 8, 32)          25632     
                                                                 
 re_lu_10 (ReLU)             (None, 8, 8, 32)          0         
                                                                 
 flatten_6 (Flatten)         (None, 2048)             

In [17]:
split = int(len(X)*0.75)
end = int(len(X))
X_, Y_ = shuffle(X[0:split], Y[0:split], random_state=0)

hist = model.fit(X_, Y_, batch_size=516, epochs=10, validation_data=(X[split:end], Y[split:end]),)

Epoch 1/10
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
800/800 [==============================] - ETA: 0s - loss: 0.6720 - accuracy: 0.5689WARNING:tensorflow:AutoGraph could not transform <function Model.make_test_function.<locals>.test_function at 0x0000015CF7FE2A68> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`

KeyboardInterrupt: 